### ISSUE TITLE
Variable not found in preprocessing

### ISSUE THREAD

**Issue by johnny12150** [rn5l/session-rec#16]
The two `path+file` and variables are missing in the `run_preprocessing.py`.

https://github.com/rn5l/session-rec/blob/d5aca66cb45030c93b7cc4d26253b0ef66f232ef/run_preprocessing.py#L78

**Comment by rn5l** [comment]
Thanks for the hint, I will fix it.
For now you can replace _path+file_ with _conf['output']['folder'] + conf['data']['prefix']_.
