### ISSUE TITLE
Better performance after fine-tune parameters

### ISSUE THREAD

**Issue by judiebig** [rn5l/session-rec#26]
Hi, I am running your code on Diginitica datasets. In concrete, I use sgnn.py (SR-GNN) as an example and find that I can get better results if I tune the parameter from lr=0.0001 l2=0.000007 lr_dc=0.63 to lr=0.001 l2=0.00001 lr_dc=0.1, just the same in the SR-GNN original paper.

The recall@20 and Mrr@20 can be improved from 30.70 15.41 to 45.52 15.91. If so, I wonder whether the conclusion reported in your paper that heuristic models get better results than such neural-based methods is proper.

Thank you and best regards.

**Comment by saraLatifi** [comment]
Hi,

To make a fair comparison, on each dataset, including Diginetica, running the random hyperparameter optimization (100 iterations) for all methods, we used the hyperparameter set that achieved the best MRR@20 as the optimal hyperparameters for the method on that dataset. Therefore, for SR-GNN, like all other methods, we ran the experiments with the found optimal set, and we reported the results of our experiments. The details of the used methodology, optimizations, experiments, and results are clearly mentioned in our paper.

Best regards
