### ISSUE TITLE
Can't run using Docker

### ISSUE THREAD

**Issue by leeway-liu** [rn5l/session-rec#9]
Hey,

Thanks for this amazing git! I pulled your docker file, but failed to run following your steps.

When I run `./dpython run_preprocesing.py conf/preprocess/window/rsc15.yml`, it is telling me that 
> python: can't open file 'run_preprocesing.py': [Errno 2] No such file or directory

When I run `./dpython run_config.py conf/in conf/out` or `./dpython run_config.py conf/example_next.yml`, it is telling me that 

> Traceback (most recent call last):
  File "run_config.py", line 12, in <module>
    import yaml
ImportError: No module named 'yaml'

I am under session-rec folder. Do you have any idea what might cause these?

**Comment by noemi-mauro** [comment]
Hi, 
> When I run ./dpython run_preprocesing.py conf/preprocess/window/rsc15.yml, it is telling me that
We notice that there is a missing "s" in the readme so it is run_preproceSSing.py with two "s".

> When I run ./dpython run_config.py conf/in conf/out or ./dpython run_config.py conf/example_next.yml, it is telling me that

For this problem, we don't really know. The dpython file is going to run a command that installs the libraries in the requirements.txt file. Inside this file, there is the pyyaml==5.1 library. Maybe you can try to change the version. When we created the repository it was working.

Thank you for your interest!

**Comment by leeway-liu** [comment]
Hey,

Yes, you are right, I checked the filename so many times, can't believe I missed it.

For the second error, it turns out my requirements.txt is empty for some reason, once I copied them back, it is working now!

Thanks again!
